import intf_libs += libcrails-design-patterns%lib{crails-design-patterns}
import intf_libs += libdatatree%lib{datatree}

lib{crails-fonticons}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-fonticons}:
{
  cxx.export.poptions = "-I$out_root/libcrails-fonticons/" "-I$src_root/libcrails-fonticons/"
  cxx.export.libs = $intf_libs
}

liba{crails-fonticons}: cxx.export.poptions += -DLIBCRAILS_FONTICONS_STATIC
libs{crails-fonticons}: cxx.export.poptions += -DLIBCRAILS_FONTICONS_SHARED

if $version.pre_release
  lib{crails-fonticons}: bin.lib.version = "-$version.project_id"
else
  lib{crails-fonticons}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
